
import { CartProvider } from '@/context/cartContext';
import { Inter } from 'next/font/google'
import './globals.css'
import foot from '../assets/img/page-elements/foot.png'
import topo from '../assets/img/page-elements/topo.png'
import Image from 'next/image'
import { AuthProvider } from '@/context/authContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'PoupaFeira',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className='relative'>
        <AuthProvider>
        <CartProvider>
       {children}
        <Image priority src={foot} width={50} className='absolute bottom-0 left-0' alt=''/>
        <Image priority src={topo} width={90} className='absolute top-0 right-0 z-0' alt=''/>
        </CartProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
