import { Inter } from 'next/font/google'
import './globals.css'
import foot from './foot.png'
import topo from './topo.png'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='relative'>
       {children}
        <Image src={foot} width={50} className='absolute bottom-0 left-0' />
        <Image src={topo} width={90} className='absolute top-0 right-0 z-0' />
      </body>
    </html>
  )
}
